### PR TITLE
chore(lint): fix code lint

### PR DESCRIPTION
**Pull request by fu050409**
Resolved: #34

### CODE REVIEW

**Review by yaoshiu — CHANGES_REQUESTED** [review]
```diff
-         #[allow(clippy::excessive_precision)]
-        let pace_range = 0.59999999999999998;
+        let pace_range = 0.6;
```

If the this value cannot eventually fit in `f64`, we might just change it to 0.6 since it does not make any difference.

**Comment by fu050409** [comment]
> ```diff
> -         #[allow(clippy::excessive_precision)]
> -        let pace_range = 0.59999999999999998;
> +        let pace_range = 0.6;
> ```
> 
> If the this value cannot eventually fit in `f64`, we might just change it to 0.6 since it does not make any difference.

This value is indeed `f64`, except that this writeup is not recommended by `clippy`. For security reasons, I ask clippy to ignore this.

**Comment by yaoshiu** [comment]
We can test it with the following code. This value does not differ from `0.6`.
```rust
assert_eq!(0.59999999999999998, 0.6);
```

**Comment by fu050409** [comment]
Fixed

**Review by yaoshiu — APPROVED** [review]

**Pull request merged**
